modLoader = "javafml"
loaderVersion = "[33,)"
license = "MIT"
issueTrackerURL = "https://github.com/MinerArcana/Adventuring-Energies/issues"

[[mods]]
    modId = "adventuringenergies"
    version = "${version}"
    displayName = "Adventuring Energies"
    logoFile = "adventuringenergies.png" #optional
    credits = "Thanks for DivineAspect for the specification writeup"
    authors = "Lance5057 and Alan19"
    description = '''
    Detailing the powers of the world which make it up and which you can attune yourself to.
    '''

[[dependencies.adventuringenergies]]
    modId = "forge"
    mandatory = true
    versionRange = "[33,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.adventuringenergies]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.2]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.curios]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.2]"
    ordering = "NONE"
    side = "BOTH"
